version: '3'
services:

 app:
  build: .
  ports:
   - "9090:9090"
  depends_on:
   - db
 db:
  image: "postgres:10.4"
  environment:
   POSTGRES_USER: root
   POSTGRES_PASSWORD: 1234567890
   POSTGRES_DB: diinfmemorias
  ports:
   - "5432:5432"